function __push__(arr, val) { arr.push(val); return arr; }
// Generated by SeedLang Compiler
// Source: SeedLang -> JavaScript
var lumen;
lumen = { w: 64, h: 36, occ1: [], emi1: [], direct1: [], gi1: [], tmp1: [], lightX: 28, lightY: 8, tick: 0 };
function make1D(n, init) {
  let arr, i;
  arr = [];
  i = 0;
  while (i < n) {
    __push__(arr, init);
    i++;
  }
  return arr;
}
function lumenInit(w, h) {
  let n, x, p1, y, p2, p3;
  lumen.w = w;
  lumen.h = h;
  lumen.lightX = (w * 0.55);
  lumen.lightY = (h * 0.22);
  lumen.tick = 0;
  n = w * h;
  lumen.occ1 = make1D(n, 0);
  lumen.emi1 = make1D(n, 0);
  lumen.direct1 = make1D(n, 0);
  lumen.gi1 = make1D(n, 0);
  lumen.tmp1 = make1D(n, 0);
  x = 0;
  while (x < w) {
    lumen.occ1[(((h - 3) * w) + x)] = 1;
    lumen.occ1[(((h - 2) * w) + x)] = 1;
    lumen.occ1[(((h - 1) * w) + x)] = 1;
    x++;
  }
  p1 = ((w * 0.2) | 0);
  y = ((h * 0.25) | 0);
  while (y < (h - 3)) {
    lumen.occ1[(y * w + p1)] = 1;
    lumen.occ1[((y * w + p1) + 1)] = 1;
    y++;
  }
  p2 = ((w * 0.48) | 0);
  y = ((h * 0.35) | 0);
  while (y < (h - 3)) {
    lumen.occ1[(y * w + p2)] = 1;
    lumen.occ1[((y * w + p2) + 1)] = 1;
    lumen.occ1[((y * w + p2) + 2)] = 1;
    y++;
  }
  p3 = ((w * 0.76) | 0);
  y = ((h * 0.28) | 0);
  while (y < (h - 3)) {
    lumen.occ1[(y * w + p3)] = 1;
    lumen.occ1[((y * w + p3) + 1)] = 1;
    y++;
  }
  lumen.emi1[(2 * w + 3)] = 1;
  lumen.emi1[((2 * w) + (w - 4))] = 0.75;
}
function lumenSetLight(x, y) {
  lumen.lightX = Math.max(0, Math.min(lumen.w, x));
  lumen.lightY = Math.max(0, Math.min(lumen.h, y));
}
function lumenShadow(x, y, lx, ly) {
  let dx, dy, dist, steps, i, t, sx, sy;
  dx = lx - x;
  dy = ly - y;
  dist = Math.sqrt(((dx * dx) + (dy * dy)));
  if (dist < 1) return 1;
  steps = ((dist * 1.15) | 0);
  if (steps < 1) steps = 1;
  i = 1;
  while (i < steps) {
    t = i / steps;
    sx = (((x + (dx * t))) | 0);
    sy = (((y + (dy * t))) | 0);
    if ((((sx >= 0) && (sx < lumen.w)) && (sy >= 0)) && (sy < lumen.h)) {
      if (lumen.occ1[((sy * lumen.w) + sx)] === 1) return 0.08;
    }
    i++;
  }
  return 1;
}
function lumenComputeDirect() {
  let radius, invRadius, y, yBase, x, i, dx, dy, d, val, atten, sh;
  radius = Math.max(10, ((lumen.w * 0.32) | 0));
  invRadius = 1 / radius;
  y = 0;
  while (y < lumen.h) {
    yBase = (y * lumen.w);
    x = 0;
    while (x < lumen.w) {
      i = yBase + x;
      if (lumen.occ1[i] === 1) {
        lumen.direct1[i] = 0;
      } else {
        dx = (lumen.lightX - x);
        dy = (lumen.lightY - y);
        d = Math.sqrt(((dx * dx) + (dy * dy)));
        val = (0.02 + (lumen.emi1[i] * 1.7));
        if (d < radius) {
          atten = (1 - (d * invRadius));
          sh = lumenShadow(x, y, lumen.lightX, lumen.lightY);
          val += atten * atten * sh;
        }
        lumen.direct1[i] = val;
      }
      x++;
    }
    y++;
  }
}
function lumenDiffuse(iterations) {
  let n, i, it, y, yBase, x, i0, base, acc, ncnt, oy, ox, nx, ny, ni, swap;
  n = (lumen.w * lumen.h);
  i = 0;
  while (i < n) {
    lumen.gi1[i] = lumen.direct1[i];
    i++;
  }
  it = 0;
  while (it < iterations) {
    y = 0;
    while (y < lumen.h) {
      yBase = (y * lumen.w);
      x = 0;
      while (x < lumen.w) {
        i0 = yBase + x;
        if (lumen.occ1[i0] === 1) {
          lumen.tmp1[i0] = 0;
        } else {
          base = (lumen.gi1[i0] * 0.34);
          acc = 0;
          ncnt = 0;
          oy = -1;
          while (oy <= 1) {
            ox = -1;
            while (ox <= 1) {
              if (!((ox === 0) && (oy === 0))) {
                nx = x + ox;
                ny = y + oy;
                if ((((nx >= 0) && (nx < lumen.w)) && (ny >= 0)) && (ny < lumen.h)) {
                  ni = ((ny * lumen.w) + nx);
                  if (lumen.occ1[ni] === 0) {
                    acc += lumen.gi1[ni];
                    ncnt++;
                  }
                }
              }
              ox++;
            }
            oy++;
          }
          if (ncnt > 0) {
            lumen.tmp1[i0] = (base + (acc / ncnt * 0.62));
          } else {
            lumen.tmp1[i0] = base;
          }
        }
        x++;
      }
      y++;
    }
    swap = lumen.gi1;
    lumen.gi1 = lumen.tmp1;
    lumen.tmp1 = swap;
    it++;
  }
}
function lumenStep() {
  lumen.tick += 1;
  lumenComputeDirect();
  lumenDiffuse(4);
  return lumen.gi1;
}
