#!/usr/bin/env node
/**
 * SeedLang 到 JavaScript 编译器
 * 将 SeedLang 代码编译成可执行的 JavaScript
 */

let Lexer, Parser;
try {
    Lexer = require('../../dist/core/lexer.js').Lexer;
    Parser = require('../../dist/core/parser.js').Parser;
} catch (e) {
    Lexer = class Lexer {
        constructor(code) { this.code = code; }
        tokenize() { return []; }
    };
    Parser = class Parser {
        constructor(tokens) { this.tokens = tokens; }
        parse() { return { type: 'Program', statements: [] }; }
    };
}

class JSCompiler {
    constructor() {
        this.indent = 0;
        this.output = [];
        this.helpers = new Set();
    }

    compile(source) {
        const lexer = new Lexer(source);
        const tokens = lexer.tokenize();
        const parser = new Parser(tokens);
        const ast = parser.parse();
        return this.compileProgram(ast);
    }

    compileProgram(node) {
        this.output = [];
        this.indent = 0;
        this.helpers.clear();

        this.emit('// Generated by SeedLang Compiler');
        this.emit('// Do not edit manually');
        this.emit('');

        for (const stmt of node.statements) {
            this.compileStatement(stmt);
        }

        this.emit('');

        let helperCode = '';
        if (this.helpers.size > 0) {
            helperCode = this.generateHelpers() + '\n';
        }

        return helperCode + this.output.join('\n');
    }

    compileStatement(node) {
        switch (node.type) {
            case 'Declaration':
                this.compileDeclaration(node);
                break;
            case 'Action':
                this.compileAction(node);
                break;
            case 'FunctionDef':
                this.compileFunctionDef(node);
                break;
            case 'AsyncFunctionDef':
                this.compileAsyncFunctionDef(node);
                break;
            case 'ClassDef':
                this.compileClassDef(node);
                break;
            case 'If':
            case 'IfStatement':
                this.compileIfStatement(node);
                break;
            case 'While':
            case 'WhileStatement':
                this.compileWhileStatement(node);
                break;
            case 'For':
            case 'ForStatement':
                this.compileForStatement(node);
                break;
            case 'Return':
            case 'ReturnStatement':
                this.compileReturnStatement(node);
                break;
            case 'Break':
            case 'BreakStatement':
                this.emit('break;');
                break;
            case 'Continue':
            case 'ContinueStatement':
                this.emit('continue;');
                break;
            case 'Try':
            case 'TryStatement':
                this.compileTryStatement(node);
                break;
            case 'Import':
                this.compileImport(node);
                break;
            case 'Export':
                this.compileExport(node);
                break;
            case 'Block':
                this.emit('{');
                this.indent++;
                for (const stmt of node.statements) {
                    this.compileStatement(stmt);
                }
                this.indent--;
                this.emit('}');
                break;
            case 'ExpressionStatement':
                if (node.expression) {
                    const expr = this.compileExpression(node.expression);
                    this.emit(`${expr};`);
                }
                break;
            default:
                if (node.expression) {
                    const expr = this.compileExpression(node.expression);
                    this.emit(`${expr};`);
                } else if (node.target) {
                    const expr = this.compileExpression(node.target);
                    this.emit(`${expr};`);
                }
        }
    }

    compileDeclaration(node) {
        const name = this.getDeclarationName(node);
        const value = node.object ? this.compileExpression(node.object) : 'undefined';
        this.emit(`let ${name} = ${value};`);
    }

    getDeclarationName(node) {
        if (node.subject) {
            if (node.subject.type === 'Identifier') {
                return node.subject.name;
            }
            return this.compileExpression(node.subject);
        }
        if (node.verb) {
            return node.verb.name;
        }
        return '_';
    }

    compileAction(node) {
        if (node.target) {
            const expr = this.compileExpression(node.target);
            this.emit(`${expr};`);
        }
    }

    compileFunctionDef(node) {
        const name = node.name;
        const params = node.params.map(p => p.name || p).join(', ');
        
        this.emit(`function ${name}(${params}) {`);
        this.indent++;
        
        for (const stmt of node.body) {
            this.compileStatement(stmt);
        }
        
        this.indent--;
        this.emit('}');
        this.emit('');
    }

    compileAsyncFunctionDef(node) {
        const name = node.name;
        const params = node.params.map(p => p.name || p).join(', ');
        
        this.emit(`async function ${name}(${params}) {`);
        this.indent++;
        
        for (const stmt of node.body) {
            this.compileStatement(stmt);
        }
        
        this.indent--;
        this.emit('}');
        this.emit('');
    }

    compileClassDef(node) {
        const name = node.name;
        const parent = node.extends ? ` extends ${node.extends}` : '';
        
        this.emit(`class ${name}${parent} {`);
        this.indent++;
        
        const constructorMethod = node.methods && node.methods.find(m => m.name === 'constructor');
        if (constructorMethod) {
            const params = constructorMethod.params.map(p => p.name || p).join(', ');
            this.emit(`constructor(${params}) {`);
            this.indent++;
            for (const stmt of constructorMethod.body) {
                this.compileStatement(stmt);
            }
            this.indent--;
            this.emit('}');
        }
        
        if (node.methods) {
            for (const method of node.methods) {
                if (method.name === 'constructor') continue;
                
                const methodName = method.name;
                const params = method.params.map(p => p.name || p).join(', ');
                this.emit(`${methodName}(${params}) {`);
                this.indent++;
                for (const stmt of method.body) {
                    this.compileStatement(stmt);
                }
                this.indent--;
                this.emit('}');
            }
        }
        
        this.indent--;
        this.emit('}');
        this.emit('');
    }

    compileIfStatement(node) {
        const condition = this.compileExpression(node.condition);
        
        this.emit(`if (${condition}) {`);
        this.indent++;
        for (const stmt of node.thenBranch) {
            this.compileStatement(stmt);
        }
        this.indent--;
        
        if (node.elseBranch && node.elseBranch.length > 0) {
            if (node.elseBranch.length === 1 && node.elseBranch[0].type === 'IfStatement') {
                this.emit('} else ' + this.compileInlineIf(node.elseBranch[0]));
                return;
            }
            this.emit('} else {');
            this.indent++;
            for (const stmt of node.elseBranch) {
                this.compileStatement(stmt);
            }
            this.indent--;
        }
        
        this.emit('}');
    }

    compileInlineIf(node) {
        const condition = this.compileExpression(node.condition);
        let result = `if (${condition}) {`;
        
        for (const stmt of node.thenBranch) {
            result += ' ' + this.compileInlineStatement(stmt);
        }
        
        if (node.elseBranch && node.elseBranch.length > 0) {
            if (node.elseBranch.length === 1 && node.elseBranch[0].type === 'IfStatement') {
                result += ' } else ' + this.compileInlineIf(node.elseBranch[0]);
            } else {
                result += ' } else {';
                for (const stmt of node.elseBranch) {
                    result += ' ' + this.compileInlineStatement(stmt);
                }
                result += ' }';
            }
        } else {
            result += ' }';
        }
        
        return result;
    }

    compileInlineStatement(node) {
        switch (node.type) {
            case 'ReturnStatement':
                return node.value ? `return ${this.compileExpression(node.value)};` : 'return;';
            case 'BreakStatement':
                return 'break;';
            case 'ContinueStatement':
                return 'continue;';
            default:
                return this.compileExpression(node.expression || node) + ';';
        }
    }

    compileWhileStatement(node) {
        const condition = this.compileExpression(node.condition);
        
        this.emit(`while (${condition}) {`);
        this.indent++;
        for (const stmt of node.body) {
            this.compileStatement(stmt);
        }
        this.indent--;
        this.emit('}');
    }

    compileForStatement(node) {
        if (node.variable && node.iterable) {
            const variable = node.variable;
            const iterable = this.compileExpression(node.iterable);
            
            this.helpers.add('range');
            this.emit(`for (const ${variable} of __range__(${iterable})) {`);
            this.indent++;
            for (const stmt of node.body) {
                this.compileStatement(stmt);
            }
            this.indent--;
            this.emit('}');
        } else if (node.init || node.condition || node.update) {
            const init = node.init ? this.compileStatementInline(node.init) : '';
            const condition = node.condition ? this.compileExpression(node.condition) : '';
            const update = node.update ? this.compileStatementInline(node.update) : '';
            
            this.emit(`for (${init}; ${condition}; ${update}) {`);
            this.indent++;
            for (const stmt of node.body) {
                this.compileStatement(stmt);
            }
            this.indent--;
            this.emit('}');
        }
    }

    compileStatementInline(node) {
        if (!node) return '';
        if (node.type === 'Action' && node.target) {
            if (node.target.type === 'Assignment') {
                const target = this.compileExpression(node.target.target);
                const value = this.compileExpression(node.target.value);
                return `${target} = ${value}`;
            }
            return this.compileExpression(node.target);
        }
        return this.compileExpression(node);
    }

    compileReturnStatement(node) {
        if (node.value) {
            const value = this.compileExpression(node.value);
            this.emit(`return ${value};`);
        } else {
            this.emit('return;');
        }
    }

    compileTryStatement(node) {
        this.emit('try {');
        this.indent++;
        const tryBody = node.tryBlock || node.body || [];
        for (const stmt of tryBody) {
            this.compileStatement(stmt);
        }
        this.indent--;
        
        if (node.catchClause || node.catchBlock) {
            const catchVar = node.catchClause?.param || node.catchVar || 'e';
            this.emit(`} catch (${catchVar}) {`);
            this.indent++;
            const catchBody = node.catchClause?.body || node.catchBlock || [];
            for (const stmt of catchBody) {
                this.compileStatement(stmt);
            }
            this.indent--;
        }
        
        if (node.finallyBlock) {
            this.emit('} finally {');
            this.indent++;
            for (const stmt of node.finallyBlock) {
                this.compileStatement(stmt);
            }
            this.indent--;
        }
        this.emit('}');
    }

    compileImport(node) {
        if (node.module) {
            const module = node.module;
            if (node.specifiers && node.specifiers.length > 0) {
                const names = node.specifiers.map(s => s.name).join(', ');
                this.emit(`const { ${names} } = require('${module}');`);
            } else {
                const name = node.default || module;
                this.emit(`const ${name} = require('${module}');`);
            }
        }
    }

    compileExport(node) {
        if (node.declaration) {
            this.compileStatement(node.declaration);
            const name = node.declaration.name || 'exported';
            this.emit(`module.exports.${name} = ${name};`);
        }
    }

    compileExpression(node) {
        if (!node) return 'undefined';
        
        switch (node.type) {
            case 'NumberLiteral':
                return String(node.value);
            case 'StringLiteral':
            case 'TextLiteral':
                return this.escapeString(node.value);
            case 'BooleanLiteral':
                return String(node.value);
            case 'NullLiteral':
                return 'null';
            case 'Identifier':
                return node.name;
            case 'ArrayLiteral':
                return this.compileArrayLiteral(node);
            case 'ObjectLiteral':
                return this.compileObjectLiteral(node);
            case 'BinaryExpression':
            case 'BinaryOp':
                return this.compileBinaryExpression(node);
            case 'LogicalExpression':
                return this.compileLogicalExpression(node);
            case 'UnaryExpression':
                return this.compileUnaryExpression(node);
            case 'CallExpression':
                return this.compileCallExpression(node);
            case 'MemberExpression':
                return this.compileMemberExpression(node);
            case 'AssignmentExpression':
            case 'Assignment':
                return this.compileAssignmentExpression(node);
            case 'ArrowFunction':
                return this.compileArrowFunction(node);
            case 'AwaitExpression':
                return this.compileAwaitExpression(node);
            case 'NewExpression':
                return this.compileNewExpression(node);
            case 'ConditionalExpression':
                return this.compileConditionalExpression(node);
            default:
                return 'undefined';
        }
    }

    compileArrayLiteral(node) {
        const elements = node.elements.map(e => this.compileExpression(e));
        return `[${elements.join(', ')}]`;
    }

    compileObjectLiteral(node) {
        const props = [];
        
        if (node.entries && Array.isArray(node.entries)) {
            for (const entry of node.entries) {
                if (entry.kind === 'property') {
                    const key = entry.key;
                    const value = this.compileExpression(entry.value);
                    if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key)) {
                        props.push(`${key}: ${value}`);
                    } else {
                        props.push(`"${key}": ${value}`);
                    }
                } else if (entry.kind === 'spread') {
                    props.push(`...${this.compileExpression(entry.value)}`);
                }
            }
        } else if (node.properties) {
            if (node.properties instanceof Map) {
                node.properties.forEach((value, key) => {
                    const compiledValue = this.compileExpression(value);
                    if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key)) {
                        props.push(`${key}: ${compiledValue}`);
                    } else {
                        props.push(`"${key}": ${compiledValue}`);
                    }
                });
            } else if (Array.isArray(node.properties)) {
                for (const prop of node.properties) {
                    const key = prop.key;
                    const value = this.compileExpression(prop.value);
                    if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(key)) {
                        props.push(`${key}: ${value}`);
                    } else {
                        props.push(`"${key}": ${value}`);
                    }
                }
            }
        }
        
        if (props.length === 0) {
            return '{}';
        }
        return `{ ${props.join(', ')} }`;
    }

    compileBinaryExpression(node) {
        const left = this.compileExpression(node.left);
        const right = this.compileExpression(node.right);
        const op = node.operator;
        
        if (op === '^') {
            this.helpers.add('pow');
            return `__pow__(${left}, ${right})`;
        }
        
        return `(${left} ${op} ${right})`;
    }

    compileLogicalExpression(node) {
        const left = this.compileExpression(node.left);
        const right = this.compileExpression(node.right);
        const op = node.operator === 'and' ? '&&' : (node.operator === 'or' ? '||' : node.operator);
        return `(${left} ${op} ${right})`;
    }

    compileUnaryExpression(node) {
        const operand = this.compileExpression(node.operand);
        const op = node.operator;
        
        if (op === 'not') {
            return `(!${operand})`;
        }
        
        return `(${op}${operand})`;
    }

    compileCallExpression(node) {
        const callee = this.compileExpression(node.callee);
        const args = node.arguments.map(a => this.compileExpression(a));
        
        const builtinMap = {
            'print': 'console.log',
            'len': '__len__',
            'push': '__push__',
            'pop': '__pop__',
            'range': '__range__',
            'upper': '__upper__',
            'lower': '__lower__',
            'trim': '__trim__',
            'split': '__split__',
            'join': '__join__',
            'keys': 'Object.keys',
            'values': 'Object.values',
            'typeOf': 'typeof',
            'abs': 'Math.abs',
            'floor': 'Math.floor',
            'ceil': 'Math.ceil',
            'round': 'Math.round',
            'sqrt': 'Math.sqrt',
            'sin': 'Math.sin',
            'cos': 'Math.cos',
            'tan': 'Math.tan',
            'min': 'Math.min',
            'max': 'Math.max',
            'random': 'Math.random',
        };
        
        const mappedCallee = builtinMap[callee] || callee;
        
        if (mappedCallee === '__len__') {
            this.helpers.add('len');
        } else if (mappedCallee === '__push__') {
            this.helpers.add('push');
        } else if (mappedCallee === '__pop__') {
            this.helpers.add('pop');
        } else if (mappedCallee === '__range__') {
            this.helpers.add('range');
        } else if (mappedCallee === '__upper__') {
            this.helpers.add('upper');
        } else if (mappedCallee === '__lower__') {
            this.helpers.add('lower');
        } else if (mappedCallee === '__trim__') {
            this.helpers.add('trim');
        } else if (mappedCallee === '__split__') {
            this.helpers.add('split');
        } else if (mappedCallee === '__join__') {
            this.helpers.add('join');
        }
        
        return `${mappedCallee}(${args.join(', ')})`;
    }

    compileMemberExpression(node) {
        const object = this.compileExpression(node.object);
        const property = node.property;
        
        if (node.computed) {
            return `${object}[${this.compileExpression(property)}]`;
        }
        
        if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(property)) {
            return `${object}.${property}`;
        }
        
        return `${object}["${property}"]`;
    }

    compileAssignmentExpression(node) {
        const left = this.compileExpression(node.left || node.target);
        const right = this.compileExpression(node.right || node.value);
        return `${left} = ${right}`;
    }

    compileArrowFunction(node) {
        const params = node.params.map(p => p.name || p).join(', ');
        const body = this.compileExpression(node.body);
        return `((${params}) => ${body})`;
    }

    compileAwaitExpression(node) {
        const argument = this.compileExpression(node.argument);
        return `(await ${argument})`;
    }

    compileNewExpression(node) {
        const callee = this.compileExpression(node.callee);
        const args = node.arguments.map(a => this.compileExpression(a));
        return `new ${callee}(${args.join(', ')})`;
    }

    compileConditionalExpression(node) {
        const test = this.compileExpression(node.test);
        const consequent = this.compileExpression(node.consequent);
        const alternate = this.compileExpression(node.alternate);
        return `(${test} ? ${consequent} : ${alternate})`;
    }

    escapeString(value) {
        return JSON.stringify(value);
    }

    emit(line) {
        this.output.push('    '.repeat(this.indent) + line);
    }

    generateHelpers() {
        const helpers = [];
        
        if (this.helpers.has('len')) {
            helpers.push(`function __len__(x) { return x.length !== undefined ? x.length : Object.keys(x).length; }`);
        }
        if (this.helpers.has('push')) {
            helpers.push(`function __push__(arr, val) { arr.push(val); return arr; }`);
        }
        if (this.helpers.has('pop')) {
            helpers.push(`function __pop__(arr) { return arr.pop(); }`);
        }
        if (this.helpers.has('range')) {
            helpers.push(`function __range__(start, end, step = 1) {
    if (end === undefined) { end = start; start = 0; }
    const result = [];
    for (let i = start; step > 0 ? i < end : i > end; i += step) {
        result.push(i);
    }
    return result;
}`);
        }
        if (this.helpers.has('pow')) {
            helpers.push(`function __pow__(base, exp) { return Math.pow(base, exp); }`);
        }
        if (this.helpers.has('upper')) {
            helpers.push(`function __upper__(s) { return s.toUpperCase(); }`);
        }
        if (this.helpers.has('lower')) {
            helpers.push(`function __lower__(s) { return s.toLowerCase(); }`);
        }
        if (this.helpers.has('trim')) {
            helpers.push(`function __trim__(s) { return s.trim(); }`);
        }
        if (this.helpers.has('split')) {
            helpers.push(`function __split__(s, sep) { return s.split(sep); }`);
        }
        if (this.helpers.has('join')) {
            helpers.push(`function __join__(arr, sep) { return arr.join(sep); }`);
        }
        
        return helpers.join('\n');
    }
}

function compile(source) {
    const compiler = new JSCompiler();
    return compiler.compile(source);
}

function compileFile(inputPath, outputPath) {
    const fs = require('fs');
    const source = fs.readFileSync(inputPath, 'utf-8');
    const js = compile(source);
    
    if (outputPath) {
        fs.writeFileSync(outputPath, js, 'utf-8');
        console.log(`Compiled: ${inputPath} -> ${outputPath}`);
    }
    
    return js;
}

module.exports = { JSCompiler, compile, compileFile };
