/**
 * SeedLang 字节码指令集（Opcode 枚举）
 * 
 * 自举约束：此模块是编译器和 VM 的共享依赖，不得反向依赖 vm.js。
 * 新代码统一通过 require('./opcodes') 导入。
 */
'use strict';

const OP = {
    NOP: 0,
    CONST: 1,       // 加载常量
    NULL: 2,        // 加载 null
    TRUE: 3,        // 加载 true
    FALSE: 4,       // 加载 false
    POP: 5,         // 弹出栈顶
    
    // 变量
    GET_GLOBAL: 10,
    SET_GLOBAL: 11,
    GET_LOCAL: 12,
    SET_LOCAL: 13,
    GET_CAPTURED: 14,  // 获取捕获的变量
    SET_CAPTURED: 15,  // 设置捕获的变量
    
    // 运算
    ADD: 20,
    SUB: 21,
    MUL: 22,
    DIV: 23,
    MOD: 24,
    NEG: 25,
    
    // 比较
    EQ: 30,
    NE: 31,
    LT: 32,
    LE: 33,
    GT: 34,
    GE: 35,
    
    // 逻辑
    AND: 40,
    OR: 41,
    NOT: 42,
    
    // 位运算
    BITAND: 43,
    BITOR: 44,
    BITXOR: 45,
    BITNOT: 46,
    SHL: 47,
    SHR: 48,
    
    // 数据结构
    ARRAY: 50,
    OBJECT: 51,
    GET: 52,
    SET: 53,
    
    // 控制流
    JUMP: 60,
    JUMP_FALSE: 61,
    JUMP_FALSE_PEEK: 62,
    CALL: 63,
    RETURN: 64,
    CLOSURE: 65,
    
    // 异常处理
    TRY: 66,
    THROW: 67,
    END_TRY: 68,
    CATCH: 69,
    SET_FINALLY: 173,
    END_FINALLY: 174,
    
    // 内置
    PRINT: 70,
    IMPORT: 71,
    CALL_BUILTIN: 72,
    
    // 异步编程
    ASYNC: 73,
    AWAIT: 74,
    
    // 类与对象
    NEW: 75,
    GET_METHOD: 76,
    SUPER_CALL: 87,
    SUPER_METHOD_CALL: 154,
    
    // 循环控制
    BREAK: 77,
    CONTINUE: 78,
    
    // 模式匹配
    MATCH: 79,
    
    // 泛型调用
    GENERIC_CALL: 80,
    
    // 并行计算
    PARALLEL: 81,
    SPAWN: 82,
    AWAIT_ALL: 83,
    
    // 协程
    YIELD: 84,
    COROUTINE: 85,
    RESUME: 86,
    CONST_SET_LOCAL: 88,
    ADD_LOCAL: 89,
    CALL0: 90,
    RETURN_LOCAL: 91,
    INC_LOCAL: 92,
    ADD_LOCAL_SET: 93,
    LT_LOCAL_CONST: 94,
    LOOP_LT: 95,
    LOOP_LT_GLOBAL: 96,
    INC_GLOBAL: 97,
    ADD_GLOBAL_SET: 98,
    ADD_CAPTURED_LOCAL: 99,
    RETURN_ADD_CAPTURED_LOCAL: 100,
    RETURN_SUB_CAPTURED_LOCAL: 107,
    RETURN_MUL_CAPTURED_LOCAL: 108,
    RETURN_DIV_CAPTURED_LOCAL: 109,
    CALL_GLOBAL_CONST1: 101,
    CONST_SET_GLOBAL: 102,
    CONST_GET_GLOBAL: 103,
    ADD_GLOBALS_SET_GLOBAL: 104,
    SET_GLOBAL_KEEP: 105,
    CALL_GLOBAL_CONST2: 106,
    GET_GLOBAL2: 110,
    MUL_GLOBAL_CONST: 111,
    ADD_GLOBAL_CONST: 112,
    SUB_GLOBAL_CONST: 113,
    DIV_GLOBALS: 114,
    MUL_GLOBALS: 115,
    ADD_GLOBAL2: 116,
    SUB_GLOBAL2: 117,
    CALL_SELF1: 118,
    LOOP_INC_GLOBAL: 119,
    LOOP_RANGE_STEP: 120,
    RETURN_ADD_LOCALS: 121,
    RETURN_SUB_LOCALS: 122,
    RETURN_MUL_LOCALS: 123,
    RETURN_DIV_LOCALS: 124,
    CALL_LEAF_GLOBAL_CONST2: 125,
    CALL_INLINE_CLOSURE1: 126,
    CLOSURE_SET_GLOBAL_KEEP: 127,
    INC_GLOBAL_JUMP: 128,
    CALL_INLINE_CLOSURE1_SET_GLOBAL: 129,
    CLOSURE_SET_GLOBAL: 130,
    CALL_INLINE_CLOSURE_SET_GLOBAL: 131,
    CLOSURE_CALL_INLINE_SET_GLOBAL: 132,
    LOOP_INC_GLOBAL_SIMPLE: 133,
    ADD_NUM_GLOBALS_SET_GLOBAL: 134,
    ADD_NUM: 135,
    FOR_COUNT: 136,
    FOR_SUM: 137,
    LEAF_ADD_GLOBAL_CONST2: 138,
    LEAF_SUB_GLOBAL_CONST2: 139,
    LEAF_MUL_GLOBAL_CONST2: 140,
    LEAF_DIV_GLOBAL_CONST2: 141,
    SELF_SUB_CONST: 142,
    RETURN_SIMPLE: 143,
    LT_CONST_RETURN_LOCAL: 144,
    SELF_SUB_CONST_RETURN: 145,
    ADD_RETURN: 146,
    SELF_SUB_CONST_CALL_SELF1: 147,
    SELF_RECURSIVE_SUB_CONST: 148,
    ARRAY_PUSH: 149,
    ARRAY_GET: 150,
    ARRAY_LEN: 151,
    FOR_NESTED_COUNT: 152,
    FOR_ADD_CONST: 153,
    ARRAY_PUSH_POP: 162,
    ADD_NUM_SET_GLOBAL: 155,
    SUB_NUM_SET_GLOBAL: 156,
    MUL_NUM_SET_GLOBAL: 157,
    LT_JIF: 158,
    LE_JIF: 159,
    GT_JIF: 160,
    GE_JIF: 161,
    ARRAY_SET: 163,
    FOR_NESTED_MUL_SUM: 166,
    FOR_SUM_RANGE_PUSH: 167,
    FOR_COUNT_EVEN: 168,
    FOR_INDEX_ASSIGN: 169,
    SET_LEN_GLOBAL_CONST: 170,
    FOR_PUSH_RANGE: 171,
    GET_CONST: 172,
    MAKE_RANGE_ARRAY: 175,

    FOR_ARRAY_SUM: 176,
    FOR_PUSH_RANGE_VAR: 177,
    FOR_ARRAY_SUM_LIT: 178,

    TAIL_CALL: 254,

    IS_ARRAY: 180,

    HALT: 255
};

const RETURN_OPS = new Set([
    OP.RETURN, OP.RETURN_SIMPLE, OP.RETURN_LOCAL,
    OP.RETURN_ADD_LOCALS, OP.RETURN_SUB_LOCALS, OP.RETURN_MUL_LOCALS, OP.RETURN_DIV_LOCALS,
    OP.RETURN_ADD_CAPTURED_LOCAL, OP.RETURN_SUB_CAPTURED_LOCAL,
    OP.RETURN_MUL_CAPTURED_LOCAL, OP.RETURN_DIV_CAPTURED_LOCAL,
    OP.ADD_RETURN
]);

const COMPUTED_RETURN_OPS = new Set([
    OP.RETURN_LOCAL,
    OP.RETURN_ADD_LOCALS, OP.RETURN_SUB_LOCALS, OP.RETURN_MUL_LOCALS, OP.RETURN_DIV_LOCALS,
    OP.RETURN_ADD_CAPTURED_LOCAL, OP.RETURN_SUB_CAPTURED_LOCAL,
    OP.RETURN_MUL_CAPTURED_LOCAL, OP.RETURN_DIV_CAPTURED_LOCAL,
    OP.ADD_RETURN
]);

const VALID_OPCODES = new Set(Object.values(OP));

module.exports = { OP, RETURN_OPS, COMPUTED_RETURN_OPS, VALID_OPCODES };
