function __push__(arr, val) { arr.push(val); return arr; }
// Generated by SeedLang Compiler
// Source: SeedLang -> JavaScript (mirror of examples/clc/win32_stress_sustained.seed; full notes and build steps live in that file).
//
// Win32  sustained stress / stability harness（高负载持续运行）
//
// **状态显示**：默认与 particle_bench C++ 一致，用**窗口标题栏**（`win32.setWindowTitleStats` → UTF-8 `snprintf` + `SetWindowTextW`）显示 粒子 / FPS / 碰撞 / 校验 / 帧号。
// 需要录屏用的位图 HUD（大号数字、水印、心跳条）时，启动前设置环境变量 `SEED_WIN32_PIXEL_HUD=1`。
// 行为概要、构建命令、CI（SEED_WIN32_AUTOCLOSE）与跨实现对齐说明：见同目录 `win32_stress_sustained.seed`。
//
let MAX_PARTICLES, PARTICLE_CYCLE_FRAMES, PARTICLE_TIER_SLOTS, W, H, BGSTEP, DEMO_RAMP_TARGET, DEMO_RAMP_FRAMES, DEMO_HOLD_FRAMES, MAXF, bx, by, bvx, bvy, br, HUD_MAIN_SC, HUD_BRAND_SC, HUD_BG, HUD_FG, HUD_SHADOW, HUD_AC, HUD_ACCENT, HUD_BR, HUD_BR_BOX, BENCH_RNG_MOD, TIER_MODE, PIXEL_HUD, DEBUG_MODE, nowMs, inst, ep, sh, particleCount, collisions, frame, diag, lastPerfMs, smoothFps, benchRngState, FIXED_PARTICLE_N, STOP_AT_FRAMES, fpsMin, fpsMax, fpsSum, fpsSamples, instFps, holdAfterStop, dtm, cap;
MAX_PARTICLES = 20000;
PARTICLE_CYCLE_FRAMES = 600;
PARTICLE_TIER_SLOTS = 21;
particleCount = 500;
W = 640;
H = 480;
BGSTEP = 2;
DEMO_RAMP_TARGET = 8000;
DEMO_RAMP_FRAMES = 800;
DEMO_HOLD_FRAMES = 400;
MAXF = 1200;
bx = [];
by = [];
bvx = [];
bvy = [];
br = [];
collisions = 0;
frame = 0;
diag = 0;
lastPerfMs = 0;
smoothFps = 0;
HUD_MAIN_SC = 3;
HUD_BRAND_SC = 2;
HUD_BG = 4278329616;
HUD_FG = 4294938368;
HUD_SHADOW = 4280697589;
HUD_AC = 4278255615;
HUD_ACCENT = 4288487818;
HUD_BR = 4294918567;
HUD_BR_BOX = 4279376414;
BENCH_RNG_MOD = 2147483647;
benchRngState = 1;
function benchRngSeedFromEnv() {
  let s, r;
  s = win32.envInt("PARTICLE_BENCH_RNG_SEED", -1);
  if (s < 0) return 88675123;
  if (s === 0) return 1;
  r = s % BENCH_RNG_MOD;
  if (r === 0) return 1;
  return r;
}
function benchRngNext() {
  let z, hi, lo, t;
  z = benchRngState;
  hi = (z / 127773 | 0);
  lo = (z - (hi * 127773));
  t = ((16807 * lo) - (2836 * hi));
  if (t <= 0) t += BENCH_RNG_MOD;
  benchRngState = t;
  return t;
}
function init() {
  let i;
  benchRngState = benchRngSeedFromEnv();
  i = 0;
  while (i < MAX_PARTICLES) {
    __push__(bx, (24 + (benchRngNext() % (W - 48))));
    __push__(by, (24 + (benchRngNext() % (H - 48))));
    __push__(bvx, ((benchRngNext() % 10) - 5));
    __push__(bvy, ((benchRngNext() % 10) - 5));
    __push__(br, (4 + (benchRngNext() % 7)));
    i++;
  }
}
function fillRect(x0, y0, rw, rh, c) {
  let yy, xx, px, py;
  yy = 0;
  while (yy < rh) {
    xx = 0;
    while (xx < rw) {
      px = x0 + xx;
      py = y0 + yy;
      if ((((px >= 0) && (px < W)) && (py >= 0)) && (py < H)) win32.setPixel(px, py, c);
      xx++;
    }
    yy++;
  }
}
function digitPat(d, rz) {
  if (d === 0) {
    if (rz === 0) return 31;
    if (rz === 1) return 17;
    if (rz === 2) return 21;
    if (rz === 3) return 21;
    if (rz === 4) return 21;
    if (rz === 5) return 17;
    return 31;
  }
  if (d === 1) {
    if (rz === 0) return 4;
    if (rz === 1) return 12;
    if (rz === 2) return 4;
    if (rz === 3) return 4;
    if (rz === 4) return 4;
    if (rz === 5) return 4;
    return 14;
  }
  if (d === 2) {
    if (rz === 0) return 31;
    if (rz === 1) return 16;
    if (rz === 2) return 8;
    if (rz === 3) return 4;
    if (rz === 4) return 2;
    if (rz === 5) return 1;
    return 31;
  }
  if (d === 3) {
    if (rz === 0) return 31;
    if (rz === 1) return 16;
    if (rz === 2) return 14;
    if (rz === 3) return 16;
    if (rz === 4) return 16;
    if (rz === 5) return 16;
    return 31;
  }
  if (d === 4) {
    if (rz === 0) return 17;
    if (rz === 1) return 17;
    if (rz === 2) return 31;
    if (rz === 3) return 16;
    if (rz === 4) return 16;
    if (rz === 5) return 16;
    return 0;
  }
  if (d === 5) {
    if (rz === 0) return 31;
    if (rz === 1) return 1;
    if (rz === 2) return 1;
    if (rz === 3) return 30;
    if (rz === 4) return 16;
    if (rz === 5) return 16;
    return 31;
  }
  if (d === 6) {
    if (rz === 0) return 30;
    if (rz === 1) return 1;
    if (rz === 2) return 1;
    if (rz === 3) return 30;
    if (rz === 4) return 17;
    if (rz === 5) return 17;
    return 30;
  }
  if (d === 7) {
    if (rz === 0) return 31;
    if (rz === 1) return 16;
    if (rz === 2) return 8;
    if (rz === 3) return 8;
    if (rz === 4) return 4;
    if (rz === 5) return 4;
    return 4;
  }
  if (d === 8) {
    if (rz === 0) return 30;
    if (rz === 1) return 17;
    if (rz === 2) return 17;
    if (rz === 3) return 30;
    if (rz === 4) return 17;
    if (rz === 5) return 17;
    return 30;
  }
  if (d === 9) {
    if (rz === 0) return 30;
    if (rz === 1) return 17;
    if (rz === 2) return 17;
    if (rz === 3) return 30;
    if (rz === 4) return 16;
    if (rz === 5) return 16;
    return 30;
  }
  return 0;
}
function bitAt(m, cx) {
  let div, k;
  div = 1;
  k = 4 - cx;
  while (k > 0) {
    div *= 2;
    k--;
  }
  return ((m / div | 0) & 1);
}
function plotDigit(d, ox, oy, sc, col) {
  let rz, m, cx, sy, sx, px, py;
  rz = 0;
  while (rz < 7) {
    m = digitPat(d, rz);
    cx = 0;
    while (cx < 5) {
      if (bitAt(m, cx) === 1) {
        sy = 0;
        while (sy < sc) {
          sx = 0;
          while (sx < sc) {
            px = ((ox + (cx * sc)) + sx);
            py = ((oy + (rz * sc)) + sy);
            if ((((px >= 0) && (px < W)) && (py >= 0)) && (py < H)) win32.setPixel(px, py, col);
            sx++;
          }
          sy++;
        }
      }
      cx++;
    }
    rz++;
  }
}
function plotDigitNice(d, ox, oy, sc, fg, sh) {
  let sd;
  sd = 2;
  if (sc <= 1) sd = 1;
  plotDigit(d, (ox + sd), (oy + sd), sc, sh);
  plotDigit(d, ox, oy, sc, fg);
}
function drawNumber(val, nd, ox, oy, sc, col) {
  let vi, pow10, kk, dg;
  vi = 0;
  while (vi < nd) {
    pow10 = 1;
    kk = (nd - 1 - vi);
    while (kk > 0) {
      pow10 *= 10;
      kk--;
    }
    dg = ((val / pow10 | 0) % 10);
    plotDigit(dg, (ox + (vi * (5 * sc + 2))), oy, sc, col);
    vi++;
  }
}
function drawNumberNice(val, nd, ox, oy, sc, fg, sh) {
  let vi, pow10, kk, dg;
  vi = 0;
  while (vi < nd) {
    pow10 = 1;
    kk = (nd - 1 - vi);
    while (kk > 0) {
      pow10 *= 10;
      kk--;
    }
    dg = ((val / pow10 | 0) % 10);
    plotDigitNice(dg, (ox + (vi * (5 * sc + 2))), oy, sc, fg, sh);
    vi++;
  }
}
function letterPat(li, rz) {
  if (li === 0) {
    if (rz === 0) return 31;
    if (rz === 1) return 17;
    if (rz === 2) return 16;
    if (rz === 3) return 31;
    if (rz === 4) return 1;
    if (rz === 5) return 17;
    return 31;
  }
  if (li === 1) {
    if (rz === 0) return 31;
    if (rz === 1) return 16;
    if (rz === 2) return 16;
    if (rz === 3) return 31;
    if (rz === 4) return 16;
    if (rz === 5) return 16;
    return 31;
  }
  if (li === 2) {
    if (rz === 0) return 30;
    if (rz === 1) return 17;
    if (rz === 2) return 17;
    if (rz === 3) return 17;
    if (rz === 4) return 17;
    if (rz === 5) return 17;
    return 14;
  }
  if (li === 3) {
    if (rz === 0) return 16;
    if (rz === 1) return 16;
    if (rz === 2) return 16;
    if (rz === 3) return 16;
    if (rz === 4) return 16;
    if (rz === 5) return 16;
    return 31;
  }
  if (li === 4) {
    if (rz === 0) return 14;
    if (rz === 1) return 17;
    if (rz === 2) return 17;
    if (rz === 3) return 31;
    if (rz === 4) return 17;
    if (rz === 5) return 17;
    return 17;
  }
  if (li === 5) {
    if (rz === 0) return 17;
    if (rz === 1) return 27;
    if (rz === 2) return 21;
    if (rz === 3) return 19;
    if (rz === 4) return 17;
    if (rz === 5) return 17;
    return 17;
  }
  if (li === 6) {
    if (rz === 0) return 30;
    if (rz === 1) return 17;
    if (rz === 2) return 16;
    if (rz === 3) return 23;
    if (rz === 4) return 17;
    if (rz === 5) return 17;
    return 30;
  }
  if (li === 7) {
    if (rz === 0) return 31;
    if (rz === 1) return 17;
    if (rz === 2) return 17;
    if (rz === 3) return 30;
    if (rz === 4) return 17;
    if (rz === 5) return 17;
    return 17;
  }
  if (li === 8) {
    if (rz === 0) return 30;
    if (rz === 1) return 17;
    if (rz === 2) return 17;
    if (rz === 3) return 30;
    if (rz === 4) return 17;
    if (rz === 5) return 17;
    return 17;
  }
  return 0;
}
function plotLetter(li, ox, oy, sc, col) {
  let rz, m, cx, sy, sx, px, py;
  rz = 0;
  while (rz < 7) {
    m = letterPat(li, rz);
    cx = 0;
    while (cx < 5) {
      if (bitAt(m, cx) === 1) {
        sy = 0;
        while (sy < sc) {
          sx = 0;
          while (sx < sc) {
            px = ((ox + (cx * sc)) + sx);
            py = ((oy + (rz * sc)) + sy);
            if ((((px >= 0) && (px < W)) && (py >= 0)) && (py < H)) win32.setPixel(px, py, col);
            sx++;
          }
          sy++;
        }
      }
      cx++;
    }
    rz++;
  }
}
function plotLetterNice(li, ox, oy, sc, fg, sh) {
  let sd;
  sd = 2;
  if (sc <= 1) sd = 1;
  plotLetter(li, (ox + sd), (oy + sd), sc, sh);
  plotLetter(li, ox, oy, sc, fg);
}
function drawSeedLangBrand(ox, oy, brSc, fg, sh) {
  let gap;
  gap = (5 * brSc + 3);
  plotLetterNice(0, ox, oy, brSc, fg, sh);
  plotLetterNice(1, (ox + gap), oy, brSc, fg, sh);
  plotLetterNice(0, (ox + (2 * gap)), oy, brSc, fg, sh);
  plotLetterNice(2, (ox + (3 * gap)), oy, brSc, fg, sh);
  plotLetterNice(3, (ox + (4 * gap)), oy, brSc, fg, sh);
  plotLetterNice(4, (ox + (5 * gap)), oy, brSc, fg, sh);
  plotLetterNice(5, (ox + (6 * gap)), oy, brSc, fg, sh);
  plotLetterNice(6, (ox + (7 * gap)), oy, brSc, fg, sh);
}
function drawFPSWord(ox, oy, sc, fg, sh) {
  let gap;
  gap = (5 * sc + 3);
  plotLetterNice(7, ox, oy, sc, fg, sh);
  plotLetterNice(8, (ox + gap), oy, sc, fg, sh);
  plotLetterNice(0, (ox + (2 * gap)), oy, sc, fg, sh);
}
function drawVideoHud(fr, colls, dg, fpsDisp, partCt) {
  let rowy, stepBig, sepH, boy, fpsRowY, partRowY, bandH, fshow, cshow, hshow, ox0, sep1, ox1, sep2, ox2, bw, box, fpsOx, fpsCap, pcap, hb;
  rowy = 10;
  stepBig = (5 * HUD_MAIN_SC + 4);
  sepH = 7 * HUD_MAIN_SC;
  boy = (rowy + sepH + 14);
  fpsRowY = ((boy + (7 * HUD_BRAND_SC)) + 16);
  partRowY = ((fpsRowY + (7 * HUD_BRAND_SC)) + 12);
  bandH = (partRowY + sepH + 16);
  fillRect(0, 0, W, bandH, HUD_BG);
  fshow = fr % 100000000;
  cshow = colls % 10000;
  hshow = dg % 1000000;
  ox0 = 10;
  drawNumberNice(fshow, 8, ox0, rowy, HUD_MAIN_SC, HUD_FG, HUD_SHADOW);
  sep1 = ((ox0 + (8 * stepBig)) + 10);
  fillRect(sep1, rowy, 5, sepH, HUD_AC);
  ox1 = sep1 + 18;
  drawNumberNice(cshow, 4, ox1, rowy, HUD_MAIN_SC, HUD_FG, HUD_SHADOW);
  sep2 = ((ox1 + (4 * stepBig)) + 10);
  fillRect(sep2, rowy, 5, sepH, HUD_AC);
  ox2 = sep2 + 18;
  drawNumberNice(hshow, 6, ox2, rowy, HUD_MAIN_SC, HUD_FG, HUD_SHADOW);
  bw = ((8 * (5 * HUD_BRAND_SC + 3)) + 8);
  box = (W - bw - 12);
  fillRect((box - 6), (boy - 4), (bw + 12), (7 * HUD_BRAND_SC + 10), HUD_BR_BOX);
  drawSeedLangBrand(box, boy, HUD_BRAND_SC, HUD_BR, HUD_SHADOW);
  drawFPSWord(12, fpsRowY, HUD_BRAND_SC, HUD_ACCENT, HUD_SHADOW);
  fpsOx = ((12 + (3 * (5 * HUD_BRAND_SC + 3))) + 16);
  fpsCap = fpsDisp;
  if (fpsCap > 999) fpsCap = 999;
  drawNumberNice(fpsCap, 3, fpsOx, (fpsRowY - 2), HUD_MAIN_SC, HUD_FG, HUD_SHADOW);
  pcap = partCt;
  if (pcap > 99999) pcap = 99999;
  drawNumberNice(pcap, 5, 12, partRowY, HUD_MAIN_SC, HUD_AC, HUD_SHADOW);
  hb = fr % 640;
  fillRect(hb, (H - 5), 48, 5, HUD_AC);
  fillRect(((hb + 220) % 640), (H - 5), 16, 5, HUD_FG);
}
function particlesForFrame(fr) {
  let slot, denom;
  if (FIXED_PARTICLE_N >= 0) {
    if (FIXED_PARTICLE_N > MAX_PARTICLES) return MAX_PARTICLES;
    return FIXED_PARTICLE_N;
  }
  if (TIER_MODE > 0) {
    slot = ((fr / PARTICLE_CYCLE_FRAMES | 0) % PARTICLE_TIER_SLOTS);
    if (slot === 0) return 500;
    return slot * 1000;
  }
  if (fr < DEMO_RAMP_FRAMES) {
    denom = DEMO_RAMP_FRAMES - 1;
    if (denom < 1) return DEMO_RAMP_TARGET;
    return ((fr * DEMO_RAMP_TARGET / denom) | 0);
  }
  return DEMO_RAMP_TARGET;
}
function step() {
  let i, r;
  i = 0;
  while (i < particleCount) {
    bx[i] += bvx[i];
    by[i] += bvy[i];
    r = br[i];
    if (bx[i] < r) {
      bx[i] = r;
      bvx[i] = (0 - bvx[i]);
    }
    if (bx[i] > (W - r)) {
      bx[i] = W - r;
      bvx[i] = (0 - bvx[i]);
    }
    if (by[i] < r) {
      by[i] = r;
      bvy[i] = (0 - bvy[i]);
    }
    if (by[i] > (H - r)) {
      by[i] = H - r;
      bvy[i] = (0 - bvy[i]);
    }
    i++;
  }
}
function collideResolve() {
  let i, j, dx, dy, d2, md, sx, sy;
  collisions = 0;
  i = 0;
  while (i < particleCount) {
    j = i + 1;
    while (j < particleCount) {
      dx = (bx[j] - bx[i]);
      dy = (by[j] - by[i]);
      d2 = ((dx * dx) + (dy * dy));
      md = (br[i] + br[j]);
      if ((d2 > 0) && (d2 < (md * md))) {
        collisions++;
        sx = bvx[i];
        bvx[i] = bvx[j];
        bvx[j] = sx;
        sy = bvy[i];
        bvy[i] = bvy[j];
        bvy[j] = sy;
        if (dx > 0) {
          bx[i] -= 2;
          bx[j] += 2;
        }
        if (dx < 0) {
          bx[i] += 2;
          bx[j] -= 2;
        }
        if (dx === 0) {
          if (dy > 0) {
            by[i] -= 2;
            by[j] += 2;
          }
          if (dy < 0) {
            by[i] += 2;
            by[j] -= 2;
          }
        }
      }
      j++;
    }
    i++;
  }
}
function bgColor(x, y, t) {
  let bb, gg, rr;
  bb = (((x * 59) + (t * 13)) % 220);
  gg = (((y * 47) + (t * 29)) % 220);
  rr = (((x + (y * 3)) + (t * 7)) % 220);
  return (((4278190080 + bb) + (gg * 256)) + (rr * 65536));
}
function drawBackground(t) {
  let y, x;
  y = 0;
  while (y < H) {
    x = 0;
    while (x < W) {
      win32.setPixelUnsafe(x, y, bgColor(x, y, t));
      x += BGSTEP;
    }
    y += BGSTEP;
  }
}
function ballColor(i) {
  let bb, gg, rr;
  bb = ((i * 193049) % 230);
  gg = ((i * 7919) % 230);
  rr = ((i * 503) % 230);
  return (((4278190080 + bb) + (gg * 256)) + (rr * 65536));
}
function renderDisks() {
  let i, cx, cy, r, col;
  i = 0;
  while (i < particleCount) {
    cx = bx[i];
    cy = by[i];
    r = br[i];
    col = ballColor(i);
    win32.fillCircle(cx, cy, r, col);
    i++;
  }
}
function energyProxy() {
  let s, i;
  s = 0;
  i = 0;
  while (i < particleCount) {
    s += (bvx[i] * bvx[i]) + (bvy[i] * bvy[i]);
    i++;
  }
  return s;
}
function secondaryHeat() {
  let acc, k, u;
  acc = 0;
  k = 0;
  while (k < 24) {
    u = 0;
    while (u < 160) {
      acc += (((u * u) + (k * k * 3)) % 997);
      u++;
    }
    k++;
  }
  return acc;
}
FIXED_PARTICLE_N = win32.envInt("PARTICLE_BENCH_FIXED_N", -1);
STOP_AT_FRAMES = win32.envInt("PARTICLE_BENCH_MAX_FRAMES", 0);
TIER_MODE = win32.envInt("PARTICLE_BENCH_TIER_MODE", 0);
PIXEL_HUD = win32.envInt("SEED_WIN32_PIXEL_HUD", 0);
DEBUG_MODE = win32.envInt("PARTICLE_BENCH_DEBUG", 0);
if (DEBUG_MODE > 0) {
  if (FIXED_PARTICLE_N < 0) FIXED_PARTICLE_N = 5000;
  if (STOP_AT_FRAMES <= 0) STOP_AT_FRAMES = 300;
}
if (TIER_MODE > 0) {
  FIXED_PARTICLE_N = -1;
}
fpsMin = 999999;
fpsMax = 0;
fpsSum = 0;
fpsSamples = 0;
instFps = 0;
holdAfterStop = 0;
init();
while (win32.pollEvents()) {
  nowMs = win32.perfMillis();
  if (lastPerfMs > 0) {
    dtm = nowMs - lastPerfMs;
    if (dtm < 1) dtm = 1;
    inst = 1000 / dtm;
    instFps = inst;
    smoothFps = ((smoothFps * 24 + inst) / 25);
  }
  lastPerfMs = nowMs;
  particleCount = particlesForFrame(frame);
  drawBackground(frame);
  step();
  collideResolve();
  renderDisks();
  ep = energyProxy();
  sh = secondaryHeat();
  diag = (((((((diag * 1315423911) + (collisions * 911382323)) + ep) + sh) + frame) + bx[0]) % 2147483647);
  win32.setWindowTitleStats(particleCount, smoothFps, collisions, diag, frame);
  if (PIXEL_HUD > 0) drawVideoHud(frame, collisions, diag, smoothFps, particleCount);
  if ((DEBUG_MODE > 0) && (instFps > 0)) {
    fpsSamples++;
    fpsSum += instFps;
    if (instFps < fpsMin) fpsMin = instFps;
    if (instFps > fpsMax) fpsMax = instFps;
  }
  win32.present();
  frame++;
  cap = STOP_AT_FRAMES;
  if (cap <= 0) {
    cap = MAXF;
  } else {
    if ((MAXF > 0) && (MAXF < cap)) cap = MAXF;
  }
  if ((cap > 0) && (frame >= cap)) {
    holdAfterStop = 1;
    break;
  }
}
win32.setWindowTitleStats(particleCount, smoothFps, collisions, diag, frame);
renderDisks();
win32.present();
console.log(frame);
console.log(collisions);
console.log(diag);
if ((DEBUG_MODE > 0) && (fpsSamples > 0)) {
  console.log(fpsMin);
  console.log(fpsMax);
  console.log((fpsSum / fpsSamples));
}
if (holdAfterStop > 0) {
  while (win32.pollEvents()) {
  }
}
